name: dart_json_parsing_examples
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.1.4

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
